In [1]:
# path to user functions
import sys  
sys.path.append('../Src/')

from platform import python_version

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import importlib 
# import library
from prince import FAMD
# import user functions
import UserUtilityFunctions as uf

# set seaborn theme
sns.set_theme()

# initializing variables
RANDOM_STATE = 1776

# print versions
print("Numpy Version: " + np.__version__)
print("Pandas Version: " + pd.__version__)
print("Seaborn Version: " + sns.__version__)
print("Matplotlib Version: " + plt.matplotlib.__version__)
print("Python Version: " + python_version())

# adjust pandas display options to max
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
# adjust pandas display options to ensure full display of content
pd.set_option('display.max_colwidth', None)

Numpy Version: 1.26.4
Pandas Version: 2.2.3
Seaborn Version: 0.13.2
Matplotlib Version: 3.9.2
Python Version: 3.9.20


### Import Dataset

In [2]:
# import data
df = pd.read_pickle("../Data/Heart_ML_Prep.pkl")
df_ordinal = pd.read_pickle("../Data/Ordinal_ML_Prep.pkl")
df_numeric = pd.read_pickle("../Data/Numeric_ML_Prep.pkl")
df_nominal = pd.read_pickle("../Data/Nominal_ML_Prep.pkl")

# add to nominal dataframe
df_nominal.loc[len(df_nominal)] = 'Survival'

# shape
print(f"Heart Dataset Rows: {df.shape[0]:,} & Columns: {df.shape[1]:,}")
print(f"Nominal Features: {df_nominal.shape[0]:,}")
print(f"Ordinal Features: {df_ordinal.shape[0]:,}")
print(f"Numeric Features: {df_numeric.shape[0]:,}")

Heart Dataset Rows: 9,835 & Columns: 134
Nominal Features: 79
Ordinal Features: 14
Numeric Features: 41


#### Sanity Check

In [3]:
# initialize variables
numericCols = df_numeric.column.to_list()
nominalCols = df_nominal.column.to_list()
ordinalCols = df_ordinal.column.to_list()

# total features
print(f"Total Features: {len(numericCols) + len(nominalCols) + len(ordinalCols)}")
print(f"Total Features from DataFrame: {df.shape[1]}")

Total Features: 134
Total Features from DataFrame: 134


#### Examine Numeric

In [4]:
print(sorted(numericCols))

['Age_Addition', 'Age_Difference_CanDon', 'BMI_Addition', 'BMI_Difference_CanDon', 'BloodPH_DON', 'BloodUreaNitrogenLevel_DON', 'Creatinine_Addition_CAN', 'Creatinine_Difference_RT_CAN', 'Creatinine_Interaction_CAN', 'DistanceFromDonorHospitaltoTXCenter', 'HeightCm_Addition', 'HeightCm_Difference_CanDon', 'Hematocrit_DON', 'HemodynamicsRegistration_Addition_CAN', 'HemodynamicsRegistration_CO_CAN', 'HemodynamicsRegistration_Interaction_CAN', 'HemodynamicsTransplant_Addition_CAN', 'HemodynamicsTransplant_CO_CAN', 'HemodynamicsTransplant_Interaction_CAN', 'Hemodynamics_Addition_Difference_CAN', 'Hemodynamics_Difference_CO_RT_CAN', 'Hemodynamics_Difference_PA_DIA_RT_CAN', 'Hemodynamics_Difference_PA_MN_RT_CAN', 'Hemodynamics_Difference_PCW_RT_CAN', 'Hemodynamics_Difference_SYS_RT_CAN', 'Hemodynamics_Interaction_Difference_CAN', 'IschemicTimeHour_DON', 'LV_EjectionFractionPercent_DON', 'Level_SGOT_Addition_DON', 'Level_SGOT_Difference_AltAst_DON', 'LungPO2_DON', 'LungPO2_FIO2_DON', 'OrganRe

#### Examine Ordinal

In [5]:
print(sorted(ordinalCols))

['Antigen_Combine_Count_CAN', 'Bronchoscopy_Count_DON', 'Dialysis_Combine_Count_CAN', 'Drug_Combine_Count_DON', 'EducationLevel_CAN', 'FunctionalStatusTransplant_CAN', 'Infection_Combine_Count_DON', 'Intropes_Combine_Count_CAN', 'MedicalConditionTransplant_CAN', 'MismatchLevel_Combine_Count', 'PreviousTransplantNumber_CAN', 'PriorCardiacSurgery_Combine_Count_CAN', 'TransfusionNumber_DON', 'WorkIncome_Combine_Count_CAN']


##### Antigen_Combine_Count_CAN

In [6]:
# display
df.Antigen_Combine_Count_CAN.unique()

array([13,  6, 14,  5,  0, 15,  4, 12, 11,  9,  8,  3, 10,  7,  2, 18, 16,
       17])

In [7]:
# order
order = sorted(df.Antigen_Combine_Count_CAN.unique())
df['Antigen_Combine_Count_CAN'] = pd.Categorical(df['Antigen_Combine_Count_CAN'], categories=order, ordered=True)

# dtypes
df.Antigen_Combine_Count_CAN.dtypes

CategoricalDtype(categories=[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                  18],
, ordered=True, categories_dtype=int64)

##### Bronchoscopy_Count_DON

In [8]:
# display
df.Bronchoscopy_Count_DON.unique()

array([0, 2, 1])

In [9]:
# order
order = sorted(df.Bronchoscopy_Count_DON.unique())
df['Bronchoscopy_Count_DON'] = pd.Categorical(df['Bronchoscopy_Count_DON'], categories=order, ordered=True)

# dtypes
df.Bronchoscopy_Count_DON.dtypes

CategoricalDtype(categories=[0, 1, 2], ordered=True, categories_dtype=int64)

##### Dialysis_Combine_Count_CAN

In [10]:
# display
df.Dialysis_Combine_Count_CAN.unique()

array([0, 2, 1])

In [11]:
# order
order = sorted(df.Dialysis_Combine_Count_CAN.unique())
df['Dialysis_Combine_Count_CAN'] = pd.Categorical(df['Dialysis_Combine_Count_CAN'], categories=order, ordered=True)

# dtypes
df.Dialysis_Combine_Count_CAN.dtypes

CategoricalDtype(categories=[0, 1, 2], ordered=True, categories_dtype=int64)

##### Drug_Combine_Count_DON

In [12]:
# display
df.Drug_Combine_Count_DON.unique()

array([1, 0, 4, 2, 3])

In [13]:
# order
order = sorted(df.Drug_Combine_Count_DON.unique())
df['Drug_Combine_Count_DON'] = pd.Categorical(df['Drug_Combine_Count_DON'], categories=order, ordered=True)

# dtypes
df.Drug_Combine_Count_DON.dtypes

CategoricalDtype(categories=[0, 1, 2, 3, 4], ordered=True, categories_dtype=int64)

##### EducationLevel_CAN

In [14]:
# display
df.EducationLevel_CAN.unique()

array(['ASSOCIATE/BACHELOR DEGREE', 'POST-COLLEGE GRADUATE DEGREE',
       'HIGH SCHOOL (9-12) or GED', 'ATTENDED COLLEGE/TECHNICAL SCHOOL',
       'UNKNOWN', 'GRADE SCHOOL (0-8)', 'NONE'], dtype=object)

In [15]:
# order
order = ['NONE', 'UNKNOWN', 'GRADE SCHOOL (0-8)', 'HIGH SCHOOL (9-12) or GED', 'ATTENDED COLLEGE/TECHNICAL SCHOOL', 'ASSOCIATE/BACHELOR DEGREE', 'POST-COLLEGE GRADUATE DEGREE']
df['EducationLevel_CAN'] = pd.Categorical(df['EducationLevel_CAN'], categories=order, ordered=True)

# dtypes
df.EducationLevel_CAN.dtypes

CategoricalDtype(categories=['NONE', 'UNKNOWN', 'GRADE SCHOOL (0-8)',
                  'HIGH SCHOOL (9-12) or GED',
                  'ATTENDED COLLEGE/TECHNICAL SCHOOL',
                  'ASSOCIATE/BACHELOR DEGREE', 'POST-COLLEGE GRADUATE DEGREE'],
, ordered=True, categories_dtype=object)

##### FunctionalStatusTransplant_CAN

In [16]:
# display
df.FunctionalStatusTransplant_CAN.unique()

array(['30% - Severely disabled: hospitalization is indicated, death not imminent',
       '20% - Very sick, hospitalization necessary: active treatment necessary',
       '10% - Moribund, fatal processes progressing rapidly',
       '50% - Requires considerable assistance and frequent medical care',
       '40% - Disabled: requires special care and assistance', 'Unknown',
       '70% - Cares for self: unable to carry on normal activity or active work',
       '60% - Requires occasional assistance but is able to care for needs',
       '80% - Normal activity with effort: some symptoms of disease',
       '90% - Able to carry on normal activity: minor symptoms of disease',
       '100% - Normal, no complaints, no evidence of disease'],
      dtype=object)

In [17]:
# sort the list, placing "Unknown" first
order = ['Unknown'] + sorted(
    [status for status in df.FunctionalStatusTransplant_CAN.unique().tolist() if status != 'Unknown'],
    key=lambda x: int(x.split('%')[0])
)
print(order)

['Unknown', '10% - Moribund, fatal processes progressing rapidly', '20% - Very sick, hospitalization necessary: active treatment necessary', '30% - Severely disabled: hospitalization is indicated, death not imminent', '40% - Disabled: requires special care and assistance', '50% - Requires considerable assistance and frequent medical care', '60% - Requires occasional assistance but is able to care for needs', '70% - Cares for self: unable to carry on normal activity or active work', '80% - Normal activity with effort: some symptoms of disease', '90% - Able to carry on normal activity: minor symptoms of disease', '100% - Normal, no complaints, no evidence of disease']


In [18]:
df['FunctionalStatusTransplant_CAN'] = pd.Categorical(df['FunctionalStatusTransplant_CAN'], categories=order, ordered=True)

# dtypes
df.FunctionalStatusTransplant_CAN.dtypes

CategoricalDtype(categories=['Unknown',
                  '10% - Moribund, fatal processes progressing rapidly',
                  '20% - Very sick, hospitalization necessary: active treatment necessary',
                  '30% - Severely disabled: hospitalization is indicated, death not imminent',
                  '40% - Disabled: requires special care and assistance',
                  '50% - Requires considerable assistance and frequent medical care',
                  '60% - Requires occasional assistance but is able to care for needs',
                  '70% - Cares for self: unable to carry on normal activity or active work',
                  '80% - Normal activity with effort: some symptoms of disease',
                  '90% - Able to carry on normal activity: minor symptoms of disease',
                  '100% - Normal, no complaints, no evidence of disease'],
, ordered=True, categories_dtype=object)

##### Infection_Combine_Count_DON

In [19]:
# display
df.Infection_Combine_Count_DON.unique()

array([0, 4, 2, 3, 5])

In [20]:
# order
order = sorted(df.Infection_Combine_Count_DON.unique())
df['Infection_Combine_Count_DON'] = pd.Categorical(df['Infection_Combine_Count_DON'], categories=order, ordered=True)

# dtypes
df.Infection_Combine_Count_DON.dtypes

CategoricalDtype(categories=[0, 2, 3, 4, 5], ordered=True, categories_dtype=int64)

##### Intropes_Combine_Count_CAN

In [21]:
# display
df.Intropes_Combine_Count_CAN.unique()

array([ 0,  2, 12, 10,  5,  6,  7, 11,  1,  3,  8,  4,  9])

In [22]:
# order
order = sorted(df.Intropes_Combine_Count_CAN.unique())
df['Intropes_Combine_Count_CAN'] = pd.Categorical(df['Intropes_Combine_Count_CAN'], categories=order, ordered=True)

# dtypes
df.Intropes_Combine_Count_CAN.dtypes

CategoricalDtype(categories=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], ordered=True, categories_dtype=int64)

##### MedicalConditionTransplant_CAN

In [23]:
# display
df.MedicalConditionTransplant_CAN.unique()

array(['Not Hospitalized', 'In Intensive Care Unit',
       'Hospitalized Not in ICU'], dtype=object)

In [24]:
# order
order = ['Not Hospitalized', 'Hospitalized Not in ICU', 'In Intensive Care Unit']
df['MedicalConditionTransplant_CAN'] = pd.Categorical(df['MedicalConditionTransplant_CAN'], categories=order, ordered=True)

# dtypes
df.MedicalConditionTransplant_CAN.dtypes

CategoricalDtype(categories=['Not Hospitalized', 'Hospitalized Not in ICU',
                  'In Intensive Care Unit'],
, ordered=True, categories_dtype=object)

##### MismatchLevel_Combine_Count

In [25]:
# display
df.MismatchLevel_Combine_Count.unique()

array([4, 0, 3, 2, 1])

In [26]:
# order
order = sorted(df.MismatchLevel_Combine_Count.unique())
df['MismatchLevel_Combine_Count'] = pd.Categorical(df['MismatchLevel_Combine_Count'], categories=order, ordered=True)

# dtypes
df.MismatchLevel_Combine_Count.dtypes

CategoricalDtype(categories=[0, 1, 2, 3, 4], ordered=True, categories_dtype=int64)

##### PreviousTransplantNumber_CAN

In [27]:
# display
df.PreviousTransplantNumber_CAN.unique()

array([0, 1, 2])

In [28]:
# order
order = sorted(df.PreviousTransplantNumber_CAN.unique())
df['PreviousTransplantNumber_CAN'] = pd.Categorical(df['PreviousTransplantNumber_CAN'], categories=order, ordered=True)

# dtypes
df.PreviousTransplantNumber_CAN.dtypes

CategoricalDtype(categories=[0, 1, 2], ordered=True, categories_dtype=int64)

##### PriorCardiacSurgery_Combine_Count_CAN

In [29]:
# display
df.PriorCardiacSurgery_Combine_Count_CAN.unique()

array([0, 1, 2])

In [30]:
# order
order = sorted(df.PriorCardiacSurgery_Combine_Count_CAN.unique())
df['PriorCardiacSurgery_Combine_Count_CAN'] = pd.Categorical(df['PriorCardiacSurgery_Combine_Count_CAN'], categories=order, ordered=True)

# dtypes
df.PriorCardiacSurgery_Combine_Count_CAN.dtypes

CategoricalDtype(categories=[0, 1, 2], ordered=True, categories_dtype=int64)

##### TransfusionNumber_DON

In [31]:
# display
df.TransfusionNumber_DON.unique()

array(['NONE', '1 - 5', 'GREATER THAN 10', '6 - 10'], dtype=object)

In [32]:
# order
order = ['NONE', '1 - 5', '6 - 10', 'GREATER THAN 10']
df['TransfusionNumber_DON'] = pd.Categorical(df['TransfusionNumber_DON'], categories=order, ordered=True)

# dtypes
df.TransfusionNumber_DON.dtypes

CategoricalDtype(categories=['NONE', '1 - 5', '6 - 10', 'GREATER THAN 10'], ordered=True, categories_dtype=object)

##### WorkIncome_Combine_Count_CAN

In [33]:
# display
df.WorkIncome_Combine_Count_CAN.unique()

array([0, 1, 2])

In [34]:
# order
order = sorted(df.WorkIncome_Combine_Count_CAN.unique())
df['WorkIncome_Combine_Count_CAN'] = pd.Categorical(df['WorkIncome_Combine_Count_CAN'], categories=order, ordered=True)

# dtypes
df.WorkIncome_Combine_Count_CAN.dtypes

CategoricalDtype(categories=[0, 1, 2], ordered=True, categories_dtype=int64)

#### Examine Nominal

In [35]:
print(sorted(nominalCols))

['AllocationType_DON', 'AntiHypertensive_DON', 'AntibodyResultHBSAB_DON', 'AntibodyResultRPR_VDRL_DON', 'Antibody_HEP_C_DON', 'AntigenDA2_DON', 'AntigenDB2_DON', 'AntigenDR2_DON', 'ArginnieManagement_DON', 'BloodGroupMatchLevel', 'CMVStatus_Transplant_CAN', 'Cancer_Combined_DON', 'CardiacArrest_DON', 'CauseOfDeath_DON', 'CerebroVascularDisease_CAN', 'ChestXray_DON', 'CigaretteHistory_DON', 'CigaretteUse_CAN', 'Citizenship_CAN', 'Citizenship_DON', 'CoronaryAngiogram_DON', 'CrossMatchDone', 'DeceasedRetyped_DON', 'DefibrillatorImplantRegistration_CAN', 'Diabetes_CAN', 'Diabetes_DON', 'Diuretics_DON', 'EpsteinBarrSeroStatusTransplant_CAN', 'EpsteinBarr_IGG_DON', 'EpsteinBarr_IGM_DON', 'Ethnicity_CAN', 'Ethnicity_DON', 'FunctionalStatus_Difference_CAN', 'Gender_Difference', 'HBV_NAT_Result_CAN', 'HBV_NAT_Result_DON', 'HCV_NAT_PreTranspant_CAN', 'HCV_NAT_Result_DON', 'HEP_C_SerostatusStatus_CAN', 'HIV_NAT_PreTransplant_CAN', 'HIV_Risk_DON', 'HIV_SeroStatusTransplant_CAN', 'HeartProcedureTyp

In [36]:
# function to find binary category features
def findBinaryCategoryFeatures(data):
    binary_features = []
    for column in data.columns:
        if data[column].nunique() == 2:
            binary_features.append(column)
    return binary_features

In [37]:
# get all binary nominal cols
binaryCols = findBinaryCategoryFeatures(df[nominalCols])

In [38]:
# display
for binaryCol in binaryCols:
    print(f"{binaryCol} & {df[binaryCol].unique()}")

BloodGroupMatchLevel & ['Compatible' 'Identical']
AntiHypertensive_DON & ['No' 'Yes']
ArginnieManagement_DON & ['No' 'Yes']
Malignancy_CAN & ['No' 'Yes']
CigaretteUse_CAN & ['Yes' 'No']
VentilatorRegistration_CAN & ['No' 'Yes']
VentilatorTransplant_CAN & ['No' 'Yes']
HCV_NAT_Result_DON & ['Negative' 'Positive']
Antibody_HEP_C_DON & ['Negative' 'Positive']
HIV_Risk_DON & ['No' 'Yes']
DeceasedRetyped_DON & ['Yes' 'No']
CrossMatchDone & ['Yes' 'No']
NonHeartBeating_DON & ['No' 'Yes']
Diuretics_DON & ['No' 'Yes']
ThyroxineT4_DON & ['Yes' 'No']
PulmonaryCatheter_DON & ['No' 'Yes']
SynthicAntiDiureticHormone_DON & ['Yes' 'No']
KidneyAllocation_DON & ['No' 'Yes']
HeparinManagement_DON & ['No' 'Yes']
InsulinManagement_DON & ['Yes' 'No']
LV_EjectionFractionMedthod_DON & ['Echo' 'Angiogram']
Gender_Difference & [0 1]
LifeSupport_Combined_CAN & ['Yes' 'No']
FunctionalStatus_Difference_CAN & [0 1]
Survival & ['Living' 'Dead']


In [39]:
def reMapCol(value):
    if value in [0]:
        return 'No'
    else:
        return 'Yes'

In [40]:
# apply mapping function
for binaryCol in binaryCols:
    df[binaryCol] = df[binaryCol].apply(reMapCol).fillna(df[binaryCol])

# display
for binaryCol in binaryCols:
    print(f"{binaryCol} & {df[binaryCol].unique()}")

BloodGroupMatchLevel & ['Yes']
AntiHypertensive_DON & ['Yes']
ArginnieManagement_DON & ['Yes']
Malignancy_CAN & ['Yes']
CigaretteUse_CAN & ['Yes']
VentilatorRegistration_CAN & ['Yes']
VentilatorTransplant_CAN & ['Yes']
HCV_NAT_Result_DON & ['Yes']
Antibody_HEP_C_DON & ['Yes']
HIV_Risk_DON & ['Yes']
DeceasedRetyped_DON & ['Yes']
CrossMatchDone & ['Yes']
NonHeartBeating_DON & ['Yes']
Diuretics_DON & ['Yes']
ThyroxineT4_DON & ['Yes']
PulmonaryCatheter_DON & ['Yes']
SynthicAntiDiureticHormone_DON & ['Yes']
KidneyAllocation_DON & ['Yes']
HeparinManagement_DON & ['Yes']
InsulinManagement_DON & ['Yes']
LV_EjectionFractionMedthod_DON & ['Yes']
Gender_Difference & ['No' 'Yes']
LifeSupport_Combined_CAN & ['Yes']
FunctionalStatus_Difference_CAN & ['No' 'Yes']
Survival & ['Yes']


In [41]:
# convert to category datatype
df = uf.toCategory(df, binaryCols).copy()

In [42]:
# descibe nominal
df[nominalCols].describe().T

,count,unique,top,freq
BloodGroupMatchLevel,9835,1,Yes,9835
InotropicAgent_DON,9835,7,Missing,6433
HeavyAlcoholUse_DON,9835,3,No,7838
AntiHypertensive_DON,9835,1,Yes,9835
ArginnieManagement_DON,9835,1,Yes,9835
PrimaryDiagnosisType_CAN,9835,34,DILATED MYOPATHY: IDIOPATHIC,3487
CauseOfDeath_DON,9835,5,ANOXIA,4157
InfectionTherapyIV_CAN,9835,4,No,8889
AntigenDR2_DON,9835,3,Positive,9316
Citizenship_CAN,9835,4,US Citizen,9452


In [43]:
df[ordinalCols].describe().T

,count,unique,top,freq
PreviousTransplantNumber_CAN,9835,3,0,9549
EducationLevel_CAN,9835,7,HIGH SCHOOL (9-12) or GED,3565
FunctionalStatusTransplant_CAN,9835,11,"20% - Very sick, hospitalization necessary: active treatment necessary",3166
MedicalConditionTransplant_CAN,9835,3,Not Hospitalized,4311
TransfusionNumber_DON,9835,4,NONE,5041
Antigen_Combine_Count_CAN,9835,18,6,4164
Bronchoscopy_Count_DON,9835,3,0,8325
Drug_Combine_Count_DON,9835,5,0,3562
Dialysis_Combine_Count_CAN,9835,3,0,9333
Infection_Combine_Count_DON,9835,5,2,5721


### Scale Numeric Features

In [44]:
from sklearn.preprocessing import MinMaxScaler

# initialize MinMaxScaler
scale = MinMaxScaler(feature_range=(1, 10))

# scale & transform
df[numericCols] = scale.fit_transform(df[numericCols])


In [45]:
import warnings
from pandas.errors import PerformanceWarning
warnings.filterwarnings("ignore", category=PerformanceWarning)
# import library
from prince import FAMD

# Initialize FAMD
famd = FAMD(
    n_components=2,             # Number of dimensions to keep
    n_iter=10,                  # Number of iterations for the SVD algorithm
    random_state=RANDOM_STATE,  # For reproducibility
    engine="sklearn"
)

# Fit the model and transform the data
famd_results = famd.fit_transform(df)

In [117]:
famd.column_coordinates_

component,0,1
variable,,
HemodynamicsRegistration_CO_CAN,1.983870e-05,1.104804e-03
TotalDayWaitList_CAN,1.977266e-04,3.248631e-06
HemodynamicsTransplant_CO_CAN,2.968035e-04,1.368166e-03
BloodUreaNitrogenLevel_DON,6.097596e-03,1.371217e-04
IschemicTimeHour_DON,7.991149e-04,1.107908e-04
DistanceFromDonorHospitaltoTXCenter,7.142774e-04,1.195591e-03
LungPO2_DON,1.979094e-03,7.213486e-06
LV_EjectionFractionPercent_DON,2.121143e-05,3.518500e-03
LungPO2_FIO2_DON,2.717253e-03,2.952819e-03


In [116]:
famd.column_correlations(famd_results)

NotImplementedError: FAMD inherits from PCA, but this method is not implemented yet

In [112]:
famd_results.head()

component,0,1
0,-1.005029,-0.857279
1,-0.089404,-18.508709
2,-1.386525,5.498651
3,-4.396351,10.016012
4,-2.157195,3.628765


In [107]:
principal_components.shape

(9835, 2)

In [46]:
# Eigenvalues
famd.eigenvalues_summary

,eigenvalue,% of variance,% of variance (cumulative)
component,,,
0,175.915,1.54%,1.54%
1,160.032,1.41%,2.95%


In [47]:
# Contributions
(
    famd.row_contributions_
    .sort_values(0, ascending=False)
    .head(5)
    .style.format('{:.3%}')
)

component,0,1
3154,1.773%,0.008%
7987,1.750%,0.011%
7775,1.544%,0.003%
8018,1.525%,0.002%
6726,1.485%,0.003%


In [48]:
# Coordinates
famd.row_coordinates(df).head()

component,0,1
0,-1.005029,-0.857279
1,-0.089404,-18.508709
2,-1.386525,5.498651
3,-4.396351,10.016012
4,-2.157195,3.628765


In [73]:
column_coordinates = famd.column_coordinates_

In [113]:
print(f"total Features After Encoding Count: {len(famd.feature_names_in_)}")
print(f"Numeric Feature Count: {len(famd.num_cols_)}")
print(f"Category Feature count: {len(famd.cat_cols_)}")

total Features After Encoding Count: 378
Numeric Feature Count: 41
Category Feature count: 93


In [78]:
famd.percentage_of_variance_

array([1.54487594, 1.40538981])

In [51]:
# Contributions
(
    famd.row_contributions_
    .sort_values(0, ascending=False)
    .head(5)
    .style.format('{:.3%}')
)

component,0,1
3154,1.773%,0.008%
7987,1.750%,0.011%
7775,1.544%,0.003%
8018,1.525%,0.002%
6726,1.485%,0.003%


In [56]:
famd.column_contributions_.style.format('{:.03%}')

component,0,1
variable,,
HemodynamicsRegistration_CO_CAN,0.000%,0.001%
TotalDayWaitList_CAN,0.000%,0.000%
HemodynamicsTransplant_CO_CAN,0.000%,0.001%
BloodUreaNitrogenLevel_DON,0.003%,0.000%
IschemicTimeHour_DON,0.000%,0.000%
DistanceFromDonorHospitaltoTXCenter,0.000%,0.001%
LungPO2_DON,0.001%,0.000%
LV_EjectionFractionPercent_DON,0.000%,0.002%
LungPO2_FIO2_DON,0.002%,0.002%


In [95]:
famd.scree_plot()

alt.Chart(...)

In [57]:
famd.cumulative_percentage_of_variance_

array([1.54487594, 2.95026574])

In [68]:
famd.eigenvalues_summary

,eigenvalue,% of variance,% of variance (cumulative)
component,,,
0,175.915,1.54%,1.54%
1,160.032,1.41%,2.95%


In [72]:
# Contributions
(
    famd.row_contributions_
    .sort_values(0, ascending=False)
    .head(5)
    .style.format('{:.5%}')
)

component,0,1
3154,1.77259%,0.00798%
7987,1.74977%,0.01088%
7775,1.54415%,0.00346%
8018,1.52541%,0.00164%
6726,1.48528%,0.00288%
